# config/_default/menus.en.toml

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20


[[main]]
  name = "Professional"
  pageRef = "professional"
  weight = 20

[[main]]
  name = "Papers"
  pageRef = "papers"
  weight = 30

[[main]]
  name = "Presentations"
  pageRef = "presentations"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50
