# config/_default/menus.en.toml

[[main]]
  name = "Professional"
  pageRef = "professional"
  weight = 10

[[main]]
  name = "Papers"
  pageRef = "papers"
  weight = 20

[[main]]
  name = "Presentations"
  pageRef = "presentations"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40

[[main]]
  name = "GitHub"
  url = "https://github.com/congyewang"
  weight = 50
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 60
  [main.params]
    action = "search"
    icon = "search"
